/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package first_page;

import ankh.morpork.AnkhMorpork;
import static first_page.first_page.active_turn;
import static first_page.first_page.image1;
import static first_page.first_page.playerObj;
import static first_page.second_page.p;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.JRadioButton;

/**
 *
 * @author user
 */
public class gameBoard extends javax.swing.JFrame {

    
    
AnkhMorpork obj = new AnkhMorpork();
String cards ="";
static int one = 1;
public static Player p;
String[] s1;
static beginTurn bt = new beginTurn();
static selectedCard sc = new selectedCard();
static cardDetails cd;
BufferedImage img = null;
String selectedCard;
public static Integer[] no_for_symbols = new Integer[4];
static int total_symbols = 0;
public static Symbols sym = new Symbols();

    /**
     * Creates new form gameBoard
     */
    public gameBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tm1 = new javax.swing.JLabel();
        demon3 = new javax.swing.JLabel();
        Rmin1 = new javax.swing.JLabel();
        Ymin1 = new javax.swing.JLabel();
        Gbuild1 = new javax.swing.JLabel();
        Rbuild1 = new javax.swing.JLabel();
        Bbuild1 = new javax.swing.JLabel();
        Ybuild1 = new javax.swing.JLabel();
        Gmin1 = new javax.swing.JLabel();
        Bmin1 = new javax.swing.JLabel();
        troll1 = new javax.swing.JLabel();
        demon4 = new javax.swing.JLabel();
        troll3 = new javax.swing.JLabel();
        troll2 = new javax.swing.JLabel();
        demon2 = new javax.swing.JLabel();
        demon1 = new javax.swing.JLabel();
        tm2 = new javax.swing.JLabel();
        tm3 = new javax.swing.JLabel();
        tm4 = new javax.swing.JLabel();
        tm5 = new javax.swing.JLabel();
        tm6 = new javax.swing.JLabel();
        tm7 = new javax.swing.JLabel();
        tm8 = new javax.swing.JLabel();
        tm9 = new javax.swing.JLabel();
        tm10 = new javax.swing.JLabel();
        tm11 = new javax.swing.JLabel();
        tm12 = new javax.swing.JLabel();
        Rmin2 = new javax.swing.JLabel();
        Rmin3 = new javax.swing.JLabel();
        Rmin4 = new javax.swing.JLabel();
        Rmin5 = new javax.swing.JLabel();
        Rmin6 = new javax.swing.JLabel();
        Rmin7 = new javax.swing.JLabel();
        Rmin8 = new javax.swing.JLabel();
        Rmin9 = new javax.swing.JLabel();
        Rmin10 = new javax.swing.JLabel();
        Rmin11 = new javax.swing.JLabel();
        Rmin12 = new javax.swing.JLabel();
        Rbuild2 = new javax.swing.JLabel();
        Rbuild3 = new javax.swing.JLabel();
        Rbuild4 = new javax.swing.JLabel();
        Rbuild5 = new javax.swing.JLabel();
        Rbuild6 = new javax.swing.JLabel();
        Ymin2 = new javax.swing.JLabel();
        Ymin3 = new javax.swing.JLabel();
        Ymin4 = new javax.swing.JLabel();
        Ymin5 = new javax.swing.JLabel();
        Ymin6 = new javax.swing.JLabel();
        Ymin7 = new javax.swing.JLabel();
        Ymin8 = new javax.swing.JLabel();
        Ymin9 = new javax.swing.JLabel();
        Ymin10 = new javax.swing.JLabel();
        Ymin11 = new javax.swing.JLabel();
        Ymin12 = new javax.swing.JLabel();
        Ybuild2 = new javax.swing.JLabel();
        Ybuild3 = new javax.swing.JLabel();
        Ybuild4 = new javax.swing.JLabel();
        Ybuild5 = new javax.swing.JLabel();
        Ybuild6 = new javax.swing.JLabel();
        Gmin2 = new javax.swing.JLabel();
        Gmin3 = new javax.swing.JLabel();
        Gmin4 = new javax.swing.JLabel();
        Gmin5 = new javax.swing.JLabel();
        Gmin6 = new javax.swing.JLabel();
        Gmin7 = new javax.swing.JLabel();
        Gmin8 = new javax.swing.JLabel();
        Gmin9 = new javax.swing.JLabel();
        Gmin10 = new javax.swing.JLabel();
        Gmin11 = new javax.swing.JLabel();
        Gmin12 = new javax.swing.JLabel();
        Gbuild2 = new javax.swing.JLabel();
        Gbuild3 = new javax.swing.JLabel();
        Gbuild4 = new javax.swing.JLabel();
        Gbuild5 = new javax.swing.JLabel();
        Gbuild6 = new javax.swing.JLabel();
        Bmin2 = new javax.swing.JLabel();
        Bmin3 = new javax.swing.JLabel();
        Bmin4 = new javax.swing.JLabel();
        Bmin5 = new javax.swing.JLabel();
        Bmin6 = new javax.swing.JLabel();
        Bmin7 = new javax.swing.JLabel();
        Bmin8 = new javax.swing.JLabel();
        Bmin9 = new javax.swing.JLabel();
        Bmin10 = new javax.swing.JLabel();
        Bmin11 = new javax.swing.JLabel();
        Bmin12 = new javax.swing.JLabel();
        Bbuild2 = new javax.swing.JLabel();
        Bbuild3 = new javax.swing.JLabel();
        Bbuild4 = new javax.swing.JLabel();
        Bbuild5 = new javax.swing.JLabel();
        Bbuild6 = new javax.swing.JLabel();
        Board = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        fundsLabel = new javax.swing.JLabel();
        playercardLabel = new javax.swing.JLabel();
        tmLabel = new javax.swing.JLabel();
        demonsLabel = new javax.swing.JLabel();
        trollsLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        noplayerLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        currentLabel = new javax.swing.JLabel();
        gameLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        playerAidButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        savegameButton = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        notify = new javax.swing.JLabel();
        beginTurnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1103, 800));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                place(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrange(evt);
            }
        });
        getContentPane().setLayout(null);

        tm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm1.setOpaque(true);
        getContentPane().add(tm1);
        tm1.setBounds(20, 20, 13, 13);

        demon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/demon.png"))); // NOI18N
        getContentPane().add(demon3);
        demon3.setBounds(440, 10, 10, 17);

        Rmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin1);
        Rmin1.setBounds(30, 40, 11, 10);

        Ymin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin1);
        Ymin1.setBounds(780, 40, 10, 11);

        Gbuild1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N
        getContentPane().add(Gbuild1);
        Gbuild1.setBounds(270, 60, 7, 18);

        Rbuild1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N
        getContentPane().add(Rbuild1);
        Rbuild1.setBounds(20, 60, 7, 18);

        Bbuild1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild1.setAutoscrolls(true);
        Bbuild1.setName(""); // NOI18N
        getContentPane().add(Bbuild1);
        Bbuild1.setBounds(520, 60, 7, 18);

        Ybuild1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N
        getContentPane().add(Ybuild1);
        Ybuild1.setBounds(770, 60, 7, 18);

        Gmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin1);
        Gmin1.setBounds(280, 40, 11, 11);

        Bmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin1);
        Bmin1.setBounds(530, 40, 11, 11);

        troll1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/troll.png"))); // NOI18N
        getContentPane().add(troll1);
        troll1.setBounds(300, 10, 18, 12);

        demon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/demon.png"))); // NOI18N
        getContentPane().add(demon4);
        demon4.setBounds(460, 10, 10, 17);

        troll3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/troll.png"))); // NOI18N
        getContentPane().add(troll3);
        troll3.setBounds(360, 10, 18, 12);

        troll2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/troll.png"))); // NOI18N
        getContentPane().add(troll2);
        troll2.setBounds(330, 10, 18, 12);

        demon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/demon.png"))); // NOI18N
        getContentPane().add(demon2);
        demon2.setBounds(420, 10, 10, 17);

        demon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/demon.png"))); // NOI18N
        getContentPane().add(demon1);
        demon1.setBounds(400, 10, 10, 17);

        tm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm2.setOpaque(true);
        getContentPane().add(tm2);
        tm2.setBounds(40, 20, 13, 13);

        tm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm3.setOpaque(true);
        getContentPane().add(tm3);
        tm3.setBounds(60, 20, 13, 13);

        tm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm4.setOpaque(true);
        getContentPane().add(tm4);
        tm4.setBounds(80, 20, 13, 13);

        tm5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm5.setOpaque(true);
        getContentPane().add(tm5);
        tm5.setBounds(100, 20, 13, 13);

        tm6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm6.setOpaque(true);
        getContentPane().add(tm6);
        tm6.setBounds(120, 20, 13, 13);

        tm7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm7.setOpaque(true);
        getContentPane().add(tm7);
        tm7.setBounds(140, 20, 13, 13);

        tm8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm8.setOpaque(true);
        getContentPane().add(tm8);
        tm8.setBounds(160, 20, 13, 13);

        tm9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm9.setOpaque(true);
        getContentPane().add(tm9);
        tm9.setBounds(180, 20, 13, 13);

        tm10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm10.setOpaque(true);
        getContentPane().add(tm10);
        tm10.setBounds(200, 20, 13, 13);

        tm11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm11.setOpaque(true);
        getContentPane().add(tm11);
        tm11.setBounds(220, 20, 13, 13);

        tm12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm12.setOpaque(true);
        getContentPane().add(tm12);
        tm12.setBounds(240, 20, 13, 13);

        Rmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin2);
        Rmin2.setBounds(50, 40, 11, 11);

        Rmin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin3);
        Rmin3.setBounds(70, 40, 11, 11);

        Rmin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin4);
        Rmin4.setBounds(90, 40, 11, 11);

        Rmin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin5);
        Rmin5.setBounds(130, 40, 11, 11);

        Rmin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin6);
        Rmin6.setBounds(110, 40, 11, 11);

        Rmin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin7);
        Rmin7.setBounds(150, 40, 11, 10);

        Rmin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin8);
        Rmin8.setBounds(170, 40, 11, 11);

        Rmin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin9);
        Rmin9.setBounds(190, 40, 11, 11);

        Rmin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin10);
        Rmin10.setBounds(210, 40, 11, 10);

        Rmin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin11);
        Rmin11.setBounds(230, 40, 11, 10);

        Rmin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N
        getContentPane().add(Rmin12);
        Rmin12.setBounds(250, 40, 11, 10);

        Rbuild2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N
        getContentPane().add(Rbuild2);
        Rbuild2.setBounds(40, 60, 7, 18);

        Rbuild3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N
        getContentPane().add(Rbuild3);
        Rbuild3.setBounds(60, 60, 7, 18);

        Rbuild4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N
        getContentPane().add(Rbuild4);
        Rbuild4.setBounds(80, 60, 7, 18);

        Rbuild5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N
        getContentPane().add(Rbuild5);
        Rbuild5.setBounds(100, 60, 7, 18);

        Rbuild6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N
        getContentPane().add(Rbuild6);
        Rbuild6.setBounds(120, 60, 7, 18);

        Ymin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin2);
        Ymin2.setBounds(800, 40, 10, 11);

        Ymin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin3);
        Ymin3.setBounds(820, 40, 10, 11);

        Ymin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin4);
        Ymin4.setBounds(840, 40, 10, 11);

        Ymin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin5);
        Ymin5.setBounds(860, 40, 10, 11);

        Ymin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin6);
        Ymin6.setBounds(880, 40, 10, 11);

        Ymin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin7);
        Ymin7.setBounds(900, 40, 10, 11);

        Ymin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin8);
        Ymin8.setBounds(920, 40, 10, 11);

        Ymin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin9);
        Ymin9.setBounds(940, 40, 10, 11);

        Ymin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin10);
        Ymin10.setBounds(960, 40, 10, 11);

        Ymin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin11);
        Ymin11.setBounds(980, 40, 10, 11);

        Ymin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N
        getContentPane().add(Ymin12);
        Ymin12.setBounds(950, 10, 10, 11);

        Ybuild2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N
        getContentPane().add(Ybuild2);
        Ybuild2.setBounds(790, 60, 7, 18);

        Ybuild3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N
        getContentPane().add(Ybuild3);
        Ybuild3.setBounds(810, 60, 7, 18);

        Ybuild4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N
        getContentPane().add(Ybuild4);
        Ybuild4.setBounds(830, 60, 7, 18);

        Ybuild5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N
        getContentPane().add(Ybuild5);
        Ybuild5.setBounds(850, 60, 7, 18);

        Ybuild6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N
        getContentPane().add(Ybuild6);
        Ybuild6.setBounds(870, 60, 7, 18);

        Gmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin2);
        Gmin2.setBounds(300, 40, 11, 11);

        Gmin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin3);
        Gmin3.setBounds(320, 40, 11, 11);

        Gmin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin4);
        Gmin4.setBounds(340, 40, 11, 11);

        Gmin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin5);
        Gmin5.setBounds(360, 40, 11, 11);

        Gmin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin6);
        Gmin6.setBounds(380, 40, 11, 11);

        Gmin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin7);
        Gmin7.setBounds(400, 40, 11, 11);

        Gmin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin8);
        Gmin8.setBounds(420, 40, 11, 11);

        Gmin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin9);
        Gmin9.setBounds(440, 40, 11, 11);

        Gmin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin10);
        Gmin10.setBounds(460, 40, 11, 11);

        Gmin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin11);
        Gmin11.setBounds(480, 40, 11, 11);

        Gmin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N
        getContentPane().add(Gmin12);
        Gmin12.setBounds(500, 40, 11, 11);

        Gbuild2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N
        getContentPane().add(Gbuild2);
        Gbuild2.setBounds(290, 60, 7, 20);

        Gbuild3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N
        getContentPane().add(Gbuild3);
        Gbuild3.setBounds(310, 60, 7, 18);

        Gbuild4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N
        getContentPane().add(Gbuild4);
        Gbuild4.setBounds(330, 60, 7, 18);

        Gbuild5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N
        getContentPane().add(Gbuild5);
        Gbuild5.setBounds(350, 60, 7, 18);

        Gbuild6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N
        getContentPane().add(Gbuild6);
        Gbuild6.setBounds(370, 60, 10, 18);

        Bmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin2);
        Bmin2.setBounds(550, 40, 11, 11);

        Bmin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin3);
        Bmin3.setBounds(570, 40, 11, 11);

        Bmin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin4);
        Bmin4.setBounds(590, 40, 11, 11);

        Bmin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin5);
        Bmin5.setBounds(610, 40, 11, 11);

        Bmin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin6);
        Bmin6.setBounds(630, 40, 11, 11);

        Bmin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin7);
        Bmin7.setBounds(650, 40, 10, 11);

        Bmin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin8);
        Bmin8.setBounds(670, 40, 11, 11);

        Bmin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin9);
        Bmin9.setBounds(690, 40, 11, 11);

        Bmin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin10);
        Bmin10.setBounds(710, 40, 11, 10);

        Bmin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin11);
        Bmin11.setBounds(730, 40, 11, 11);

        Bmin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N
        getContentPane().add(Bmin12);
        Bmin12.setBounds(750, 40, 11, 11);

        Bbuild2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild2.setAutoscrolls(true);
        Bbuild2.setName(""); // NOI18N
        getContentPane().add(Bbuild2);
        Bbuild2.setBounds(540, 60, 7, 18);

        Bbuild3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild3.setAutoscrolls(true);
        Bbuild3.setName(""); // NOI18N
        getContentPane().add(Bbuild3);
        Bbuild3.setBounds(560, 60, 7, 18);

        Bbuild4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild4.setAutoscrolls(true);
        Bbuild4.setName(""); // NOI18N
        getContentPane().add(Bbuild4);
        Bbuild4.setBounds(580, 60, 7, 18);

        Bbuild5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild5.setAutoscrolls(true);
        Bbuild5.setName(""); // NOI18N
        getContentPane().add(Bbuild5);
        Bbuild5.setBounds(600, 60, 7, 18);

        Bbuild6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild6.setAutoscrolls(true);
        Bbuild6.setName(""); // NOI18N
        getContentPane().add(Bbuild6);
        Bbuild6.setBounds(620, 60, 7, 18);

        Board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/board.jpg"))); // NOI18N
        getContentPane().add(Board);
        Board.setBounds(10, 90, 971, 600);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("   Bank Status");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel6.setText("Area Cards:");

        jLabel7.setText("Available Funds:");

        jLabel8.setText("Player cards Remaining:");

        jLabel9.setText("Trouble Markers:");

        jLabel10.setText("Demons:");

        jLabel11.setText("Trolls:");

        tmLabel.setText("9");

        demonsLabel.setText("4");

        trollsLabel.setText("3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fundsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(areaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trollsLabel)
                            .addComponent(demonsLabel)
                            .addComponent(tmLabel)
                            .addComponent(playercardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(areaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fundsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playercardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tmLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(demonsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(trollsLabel))
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(989, 227, 232, 243);

        jLabel2.setText("Total Players:");

        noplayerLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noplayerLabel.setMaximumSize(new java.awt.Dimension(120, 120));

        jLabel4.setText("Current Player:");

        gameLabel.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        gameLabel.setForeground(new java.awt.Color(0, 102, 255));
        gameLabel.setText("game statistic");
        gameLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(gameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(currentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(noplayerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(noplayerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(currentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(1008, 10, 270, 166);

        playerAidButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        playerAidButton.setForeground(new java.awt.Color(0, 102, 255));
        playerAidButton.setText("Player Aid Card");
        playerAidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerAidButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 102, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Give name for the file:");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        savegameButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        savegameButton.setForeground(new java.awt.Color(0, 102, 255));
        savegameButton.setText("Save Game");
        savegameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savegameButtonActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(0, 102, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        notify.setText("Please give a name for the file");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(notify))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(savegameButton)
                        .addGap(14, 14, 14)
                        .addComponent(cancel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(nameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nameText))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(playerAidButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(playerAidButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savegameButton)
                    .addComponent(cancel))
                .addGap(18, 18, 18)
                .addComponent(notify)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(989, 488, 251, 224);

        beginTurnButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        beginTurnButton.setForeground(new java.awt.Color(0, 102, 255));
        beginTurnButton.setText("Begin Turn");
        beginTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginTurnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(beginTurnButton);
        beginTurnButton.setBounds(1086, 187, 111, 29);

        setBounds(0, 0, 1322, 753);
    }// </editor-fold>//GEN-END:initComponents

    private void place(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_place
    
    }//GEN-LAST:event_place

    private void arrange(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrange
    //Demo display for TMs positions in each area
        tm1.setBounds(160, 265, 13, 13);       
        tm2.setBounds(260, 330, 13, 13); 
        tm3.setBounds(320, 125, 13, 13); 
        tm4.setBounds(480, 120, 13, 13);       
        tm5.setBounds(550, 290, 13, 13); 
        tm6.setBounds(680, 170, 13, 13);
        tm7.setBounds(670, 340, 13, 13);       
        tm8.setBounds(700, 530, 13, 13); 
        tm9.setBounds(510, 620, 13, 13);
        tm10.setBounds(460, 380, 13, 13);       
        tm11.setBounds(370, 540, 13, 13); 
        tm12.setBounds(210, 520, 13, 13);
   //Demo display for Buildings positions in each area
        Gbuild1.setBounds(180, 340, 7, 18);       
        Gbuild2.setBounds(260, 350, 7, 18);  
        Gbuild3.setBounds(210, 550, 7, 18);   
        Rbuild1.setBounds(330, 150, 7, 18);        
        Rbuild2.setBounds(480, 150, 7, 18);
        Rbuild3.setBounds(630, 260, 7, 18); 
        Bbuild1.setBounds(760, 190, 7, 18);      
        Bbuild2.setBounds(670, 380, 7, 18);
        Bbuild3.setBounds(690, 560, 7, 18);
        Ybuild1.setBounds(590, 650, 7, 18);      
        Ybuild2.setBounds(530, 410, 7, 18);
        Ybuild3.setBounds(370, 570, 7, 18);
    //Demo display for Demons positions in each area
        demon1.setBounds(580, 90, 8, 17);       
        demon2.setBounds(750, 120, 8, 17);  
        demon3.setBounds(870, 420, 8, 17);   
        demon4.setBounds(510, 430, 8, 17);      
    //Demo display for Trolls positions in each area
        troll1.setBounds(590, 410, 18, 12);       
        troll2.setBounds(860, 320, 18, 12);  
        troll3.setBounds(520, 670, 18, 12);   
    //Demo display for minions positions in area9
        Gmin4.setBounds(540, 610, 11, 11);
        Gmin5.setBounds(540, 620, 11, 11);
        Gmin6.setBounds(540, 630, 11, 11);
        Gmin7.setBounds(540, 640, 11, 11);
        Gmin8.setBounds(540, 650, 11, 11);
        Gmin9.setBounds(540, 660, 11, 11);
        Gmin10.setBounds(555, 610, 11, 11);
        Gmin11.setBounds(555, 620, 11, 11);
        Gmin12.setBounds(555, 630, 11, 11);
        Bmin4.setBounds(555, 640, 11, 11);
        Bmin5.setBounds(555, 650, 11, 11);
        Bmin6.setBounds(555, 660, 11, 11);
        
        for(int i=0;i<first_page.playerObj.length;i++){
            if(first_page.playerObj[i].Color == "red"){
        Rmin1.setBounds(200, 280, 11, 11);
        Rmin2.setBounds(570, 280, 11, 11);
        Rmin3.setBounds(710, 320, 11, 11);
            }
        if(first_page.playerObj[i].Color == "green"){
        Gmin1.setBounds(200, 290, 11, 11);
        Gmin2.setBounds(570, 290, 11, 11);
        Gmin3.setBounds(710, 330, 11, 11);
        }
        if(first_page.playerObj[i].Color == "blue"){
        Bmin1.setBounds(200, 300, 11, 11);
        Bmin2.setBounds(570, 300, 11, 11);
        Bmin3.setBounds(710, 340, 11, 11);
        }
        if(first_page.playerObj[i].Color == "yellow"){
        Ymin1.setBounds(200, 310, 11, 11);
        Ymin2.setBounds(570, 310, 11, 11);
        Ymin3.setBounds(710, 350, 11, 11);
        }
        }
    }//GEN-LAST:event_arrange

    private void playerAidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerAidButtonActionPerformed
        
        first_page.image1.setVisible(true);
        
        image1.events.setVisible(false);
        image1.imageLabel.setVisible(false);
        image1.personality.setVisible(false);
        image1.playerAid.setVisible(true);
        
    }//GEN-LAST:event_playerAidButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        cancel.setVisible(true);
        if(first_page.active_turn == -1)
            first_page.active_turn = 0;

        nameLabel.setVisible(true);
        nameText.setVisible(true);
     //   BendTurn.setVisible(false);
        savegameButton.setVisible(true);
        p = new Player();
        p.save_turn = first_page.active_turn;
        
        System.out.println("save turn variable: " + p.save_turn);        
        System.out.println("players detail:\n\t");
        
        for(int i =0;i<playerObj.length;i++){          
            System.out.println("player: " +(i+1) + "\n\t" + "Personality: " + playerObj[i].Personality + "\n\t" + "Color: " + playerObj[i].Color + "\n\t" + "Cash in hand:" +  playerObj[i].cashInHand + "\n\t" + "turn:" + playerObj[i].turn + "\n\t" + "buildings: "+ playerObj[i].buildInHand + "\n\t" + "minions: " + playerObj[i].minionInHand + "\n\t" + "cards: " +"\t" );
            for(int j=0;j<5;j++)
            System.out.println(first_page.playerObj[i].CardsInHand[j]);
        }
            

    }//GEN-LAST:event_saveButtonActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void savegameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savegameButtonActionPerformed
       
    if(nameText.getText().equals(""))
            notify.setText("Please Select a file");
        else
        {
            
        /*
        storing all the values for each players by calling ls.func()
        */

        FileOutputStream fileOut = null;
     try {
         fileOut = new FileOutputStream(nameText.getText() + ".ser");
     } catch (FileNotFoundException ex) {
         Logger.getLogger(second_page.class.getName()).log(Level.SEVERE, null, ex);
     }
         ObjectOutputStream out = null;
     try {
         out = new ObjectOutputStream(fileOut);
     } catch (IOException ex) {
         Logger.getLogger(second_page.class.getName()).log(Level.SEVERE, null, ex);
     }
     try {
         out.writeObject(playerObj);
         out.writeInt(playerObj.length);
         for(Player obj : playerObj)
             out.writeObject(obj);
         
     } catch (IOException ex) {
         Logger.getLogger(second_page.class.getName()).log(Level.SEVERE, null, ex);
     }
     try {
         out.close();
     } catch (IOException ex) {
         Logger.getLogger(second_page.class.getName()).log(Level.SEVERE, null, ex);
     }
     try {
         fileOut.close();
     } catch (IOException ex) {
         Logger.getLogger(second_page.class.getName()).log(Level.SEVERE, null, ex);
     }
         System.out.printf("Serialized data is saved in /tmp/employee.ser");
            
        }

    }//GEN-LAST:event_savegameButtonActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

        savegameButton.setVisible(false);
        nameLabel.setVisible(false);
        nameText.setVisible(false);
        cancel.setVisible(false);
        notify.setVisible(false);
            
    }//GEN-LAST:event_cancelActionPerformed

    private void beginTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginTurnButtonActionPerformed

        beginTurnButton.setEnabled(false);
        bt.setLayout(new FlowLayout()); 
        bt.setVisible(true);
        cards= "";
        bt.playerLabel.setText("Player " + (active_turn+1));
        bt.colorLabel.setText(playerObj[0].Color);
        bt.colorLabel.setForeground(Color.getColor(playerObj[0].Color));
        if(playerObj[active_turn].isHuman)
            bt.hcLabel.setText("H"); 
        else
            bt.hcLabel.setText("C");
        
        
        bt.personalityLabel.setText(playerObj[0].Personality);
        bt.cashLabel.setText(String.valueOf(playerObj[0].cashInHand));
        bt.minionsLabel.setText(String.valueOf(playerObj[0].minionInHand));
        bt.buildingsLabel.setText(String.valueOf(playerObj[0].buildInHand));
        bt.areasLabel.setText("0");
        for(int j=0;j<5;j++)
            cards += playerObj[0].CardsInHand[j] + "  ";
        
        bt.cardsLabel.setText(cards);

        // display cards in hands
        
        for(int i=0;i<playerObj[0].CardsInHand.length;i++){
    
            URL iconURL = getClass().getResource("\\green cards\\" + playerObj[0].CardsInHand[i] + ".png" );
            ImageIcon icon = new ImageIcon(iconURL);
            //seting radio button
            bt.rb[i] = new JRadioButton();
            bt.rb[i].setName(playerObj[0].CardsInHand[i]);
            bt.jp.add(bt.rb[i]);
            bt.radioGroup.add(bt.rb[i]);
            
            // setting label
            bt.lb[i] = new JLabel();
            bt.lb[i].setIcon(icon);
            bt.jp.add(bt.lb[i]);
            bt.add(bt.jp); 
                  
  
        }
        bt.rb[0].setSelected(true);
        bt.jb = new JButton("Play Card");
        bt.add(bt.jb,BorderLayout.CENTER);

        // play card button action
        
        bt.jb.addActionListener(new ActionListener() {
 
            public void actionPerformed(ActionEvent e)
            {
                bt.setVisible(false);
                sc.setLayout(new FlowLayout()); 
                sc.setVisible(true);
                sc.playerLabel.setText("Player " + (active_turn+1));
                sc.colorLabel.setText(playerObj[0].Color);
                sc.colorLabel.setForeground(Color.getColor(playerObj[0].Color));
                if(playerObj[active_turn].isHuman)
                    sc.ishumanLabel.setText("H"); 
                else
                    sc.ishumanLabel.setText("C");
            
            
                // get the name of the selected card
                
            for (Enumeration<AbstractButton> buttons = bt.radioGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

                if (button.isSelected()) {
                    selectedCard = button.getName();
                }
            }
                System.out.println("selected card:" + selectedCard);
                
            for (cardDetails s : cardDetails.values())
            {
                if (selectedCard.equals(s.toString()))
                {
                    for(int i=0;i<s.action.length;i++)
                    {
                        System.out.printf("selected card name: %s\n" ,s.getName());
                        no_for_symbols[i] = s.getAction(i);
                       System.out.printf("selected card actions: %d\n",no_for_symbols[i]);
                    }
                }
            }
            
            // getting number of symbols for selected card
            for(int i=0;i<no_for_symbols.length;i++){
                if(no_for_symbols[i] != null)
                {
                    System.out.println("no for symbol:" + no_for_symbols[i]);
                    total_symbols++;    // total number of symbols for current selected card
                }
            }

            // display symbols for selected card
            for(int i=0;i<total_symbols;i++){
               
                URL iconURL = getClass().getResource("\\symbols\\" + no_for_symbols[i] + ".png" );
                ImageIcon icon = new ImageIcon(iconURL);

                sc.cb[i] = new JCheckBox();
                
                System.out.println("nehal bhagat:" + sym.getSymbols(no_for_symbols[i]));
                sc.cb[i].setName(sym.getSymbols(no_for_symbols[i]));
                sc.jp.add(sc.cb[i]);
                sc.cb[0].setSelected(true);

                if(no_for_symbols[i] == 5)
                    sc.cb[i].setSelected(true);
                    
                sc.lb[i] = new JLabel();
                sc.lb[i].setIcon(icon);
                sc.jp.add(sc.lb[i]);
                sc.add(sc.jp); 
            }
            
                URL iconURL = getClass().getResource("\\green cards\\" + selectedCard + ".png" );
                ImageIcon icon = new ImageIcon(iconURL);
           
                sc.label = new JLabel();
                
                
            sc.label.setIcon(icon);
            sc.jp.add(sc.label);
            sc.add(sc.jp);
    /*        sc.jb = new JButton("Play Card");
            sc.add(bt.jb,BorderLayout.CENTER);
      */      
            }
   
        }); 


    }//GEN-LAST:event_beginTurnButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
  /*      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameBoard().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bbuild1;
    private javax.swing.JLabel Bbuild2;
    private javax.swing.JLabel Bbuild3;
    private javax.swing.JLabel Bbuild4;
    private javax.swing.JLabel Bbuild5;
    private javax.swing.JLabel Bbuild6;
    private javax.swing.JLabel Bmin1;
    private javax.swing.JLabel Bmin10;
    private javax.swing.JLabel Bmin11;
    private javax.swing.JLabel Bmin12;
    private javax.swing.JLabel Bmin2;
    private javax.swing.JLabel Bmin3;
    private javax.swing.JLabel Bmin4;
    private javax.swing.JLabel Bmin5;
    private javax.swing.JLabel Bmin6;
    private javax.swing.JLabel Bmin7;
    private javax.swing.JLabel Bmin8;
    private javax.swing.JLabel Bmin9;
    private javax.swing.JLabel Board;
    private javax.swing.JLabel Gbuild1;
    private javax.swing.JLabel Gbuild2;
    private javax.swing.JLabel Gbuild3;
    private javax.swing.JLabel Gbuild4;
    private javax.swing.JLabel Gbuild5;
    private javax.swing.JLabel Gbuild6;
    private javax.swing.JLabel Gmin1;
    private javax.swing.JLabel Gmin10;
    private javax.swing.JLabel Gmin11;
    private javax.swing.JLabel Gmin12;
    private javax.swing.JLabel Gmin2;
    private javax.swing.JLabel Gmin3;
    private javax.swing.JLabel Gmin4;
    private javax.swing.JLabel Gmin5;
    private javax.swing.JLabel Gmin6;
    private javax.swing.JLabel Gmin7;
    private javax.swing.JLabel Gmin8;
    private javax.swing.JLabel Gmin9;
    private javax.swing.JLabel Rbuild1;
    private javax.swing.JLabel Rbuild2;
    private javax.swing.JLabel Rbuild3;
    private javax.swing.JLabel Rbuild4;
    private javax.swing.JLabel Rbuild5;
    private javax.swing.JLabel Rbuild6;
    private javax.swing.JLabel Rmin1;
    private javax.swing.JLabel Rmin10;
    private javax.swing.JLabel Rmin11;
    private javax.swing.JLabel Rmin12;
    private javax.swing.JLabel Rmin2;
    private javax.swing.JLabel Rmin3;
    private javax.swing.JLabel Rmin4;
    private javax.swing.JLabel Rmin5;
    private javax.swing.JLabel Rmin6;
    private javax.swing.JLabel Rmin7;
    private javax.swing.JLabel Rmin8;
    private javax.swing.JLabel Rmin9;
    private javax.swing.JLabel Ybuild1;
    private javax.swing.JLabel Ybuild2;
    private javax.swing.JLabel Ybuild3;
    private javax.swing.JLabel Ybuild4;
    private javax.swing.JLabel Ybuild5;
    private javax.swing.JLabel Ybuild6;
    private javax.swing.JLabel Ymin1;
    private javax.swing.JLabel Ymin10;
    private javax.swing.JLabel Ymin11;
    private javax.swing.JLabel Ymin12;
    private javax.swing.JLabel Ymin2;
    private javax.swing.JLabel Ymin3;
    private javax.swing.JLabel Ymin4;
    private javax.swing.JLabel Ymin5;
    private javax.swing.JLabel Ymin6;
    private javax.swing.JLabel Ymin7;
    private javax.swing.JLabel Ymin8;
    private javax.swing.JLabel Ymin9;
    public javax.swing.JLabel areaLabel;
    public javax.swing.JButton beginTurnButton;
    public javax.swing.JButton cancel;
    public javax.swing.JLabel colorLabel;
    public javax.swing.JLabel currentLabel;
    private javax.swing.JLabel demon1;
    private javax.swing.JLabel demon2;
    private javax.swing.JLabel demon3;
    private javax.swing.JLabel demon4;
    public javax.swing.JLabel demonsLabel;
    public javax.swing.JLabel fundsLabel;
    public javax.swing.JLabel gameLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel nameLabel;
    public javax.swing.JTextField nameText;
    public javax.swing.JLabel noplayerLabel;
    public javax.swing.JLabel notify;
    private javax.swing.JButton playerAidButton;
    public javax.swing.JLabel playercardLabel;
    private javax.swing.JButton saveButton;
    public javax.swing.JButton savegameButton;
    private javax.swing.JLabel tm1;
    private javax.swing.JLabel tm10;
    private javax.swing.JLabel tm11;
    private javax.swing.JLabel tm12;
    private javax.swing.JLabel tm2;
    private javax.swing.JLabel tm3;
    private javax.swing.JLabel tm4;
    private javax.swing.JLabel tm5;
    private javax.swing.JLabel tm6;
    private javax.swing.JLabel tm7;
    private javax.swing.JLabel tm8;
    private javax.swing.JLabel tm9;
    public javax.swing.JLabel tmLabel;
    private javax.swing.JLabel troll1;
    private javax.swing.JLabel troll2;
    private javax.swing.JLabel troll3;
    public javax.swing.JLabel trollsLabel;
    // End of variables declaration//GEN-END:variables
}
