/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package first_page;

import static first_page.gameBoard.sc;
import java.awt.CheckboxGroup;
import java.awt.Component;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;


/**
 *
 * @author n_bhaga
 */
public class selectedCard extends javax.swing.JFrame {
    private String[] symName;

    /**
     * Creates new form selectedCard
     */
    public selectedCard() {
        initComponents();
    }
    public  JLabel[] lb = new JLabel[10];
    public JCheckBox[] cb = new JCheckBox[10];
    public JPanel jp = new JPanel();
    public JButton jb;
    public JLabel label = new JLabel();
    public CheckboxGroup cbg = new CheckboxGroup();
    public static String[] symbolName = new String[4];
    public Symbols sym = new Symbols();
    public String method;
    public static int selectedName=0;
    private int seletedNum = 0;
//    public JPanel panel = new JPanel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        playerLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        ishumanLabel = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setText("Current Player:");

        playerLabel.setText("jLabel2");

        colorLabel.setText("jLabel3");

        ishumanLabel.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(playerLabel)
                .addGap(54, 54, 54)
                .addComponent(colorLabel)
                .addGap(48, 48, 48)
                .addComponent(ishumanLabel)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(playerLabel)
                    .addComponent(colorLabel)
                    .addComponent(ishumanLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        playButton.setText("Play Symbols");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(playButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addComponent(playButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
       
         for(int i=0;i<gameBoard.total_symbols;i++){
                                
            if(sc.cb[i].isSelected()){
                symbolName[seletedNum] = sc.cb[i].getName();
                
                System.out.println("selected symbol:" + symbolName[seletedNum]);
               seletedNum++;
            }
         }
         
         for(int i=0;i<symbolName.length;i++){
            if(symbolName[i] != null)
                selectedName++;
             }
            for(int i=0;i<selectedName;i++){
            System.out.println("new selected symbol:" + symbolName[i]);
                method = symbolName[i];
                System.out.println("nehal method:" + method);
                switch(method){
                    case "Assassin":
                        sym.Assassin();
                        break;
                    case "Remove_tm":
                        sym.Remove_tm();
                        break;
                    case "Perform_text":
                        sym.Perform_text();
                        break;
                    case "Random_event":
                        sym.Random_event();
                        break;
                    case "Play_another_card":
                        sym.Play_another_card();
                        break;
                    case "Place_building":
                        sym.Place_building();
                        break;
                    case "Place_minion":
                        sym.Place_minion();
                        break;
                    case "Interrupt":
                        sym.Interrupt();
                        break;
                    case "Take_one":
                        sym.Take_one();
                        break;
                    case "Take_two":
                        sym.Take_two();
                        break;
                    case "Take_three":
                        sym.Take_three();
                        break;
                    case "Take_four":
                        sym.Take_four();
                        break;
                    case "Take_five":
                        sym.Take_five();
                        break;
                    default:
                        JOptionPane.showMessageDialog(sc, "Please enter File path", "Error", JOptionPane.WARNING_MESSAGE );
                    
                
                
                
                }
            
          
            
                
        }
             
         
// TODO add your handling code here:
    }//GEN-LAST:event_playButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectedCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectedCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectedCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectedCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectedCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel colorLabel;
    public javax.swing.JLabel ishumanLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton playButton;
    public javax.swing.JLabel playerLabel;
    // End of variables declaration//GEN-END:variables
}
